### ISSUE TITLE
Unable to parse transaction: No private key found for account ... Edgeware edge case

### ISSUE THREAD

**Issue by phillux** [paritytech/parity-signer#573]
Please note this is an edge case and should not happen for most users.

I generated a private key for Edgeware mainnet via Parity Signer, however this was before the "Edgeware" chain was an option in Signer. So I generated a key in the Kusama chain with a derivation path of `//kusama/edg`

Now, when I attempt to access the funds I moved to that address, I am hit with the error: "Unable to parse transaction: No private key found for account .... found in your signer key storage for the Edgeware chain"

I am able to "log in" via the QR code and my balance shows with the correct address on-chain, however I cannot access the private key for this account. I am only looking for a workaround, as this is an edge case and should not occur for any other user due to the way I generated the account.

**Comment by hanwencheng** [comment]
Thanks for openning this issue.

The account generated under Kusama is not expected to work for other networks. It works before is because we have some legacy accounts created with Kusama CC2 and then the network genesisHash has changed. However this functionality is removed recently as I have not think of the edge case like this.

Now I will just add the backward compatibiity to the current master. It intend to be removed after #524 . 

In the long run we would need a PR to refactor the way to list the accounts, and group them with the override network in consideration. And we do not need `custom network` group in the list in the future.

**Comment by hanwencheng** [comment]
fixed in #575

**Comment by phillux** [comment]
Still getting the "No private key found" Error for an Edgeware account that is found in the "Kusama" section.

**Comment by hanwencheng** [comment]
Hi @phillux , try delete the `//kusama//` account, back to the network select page, then Add Network Account -> Create Custom Path -> path `//kusama/ege` with network Edgeware. Then it should be able to sign in Edgeware network.

**Comment by phillux** [comment]
works
